site:
  title: Antora Docs
  start_page: component-b::index.adoc

content:
  sources:
  - url: https://gitlab.com/antora/demo/demo-component-a.git
    branches: HEAD
#  - url: https://github.com/scalable-t/st-try
#    branches: HEAD
#    start_path: antora-site/docs
  - url: https://gitlab.com/antora/demo/demo-component-b.git
    branches: [v2.0, v1.0]
    start_path: docs
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./node_modules/@antora/lunr-extension/supplemental_ui

antora:
  extensions:
    - '@antora/lunr-extension'
